apiVersion: v1
kind: Service
metadata:
    name: "apptest-62e7"
    labels:
        app: "apptest-62e7"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "apptest-62e7"