on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: restapi01.azurecr.io
        username: ${{ secrets.acr_restapi01_username }}
        password: ${{ secrets.acr_restapi01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t restapi01.azurecr.io/triforktest:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push restapi01.azurecr.io/triforktest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_triforktest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep trifork-testbd001 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace trifork-testbd001`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: trifork-testbd001
        container-registry-url: restapi01.azurecr.io
        container-registry-username: ${{ secrets.acr_restapi01_username }}
        container-registry-password: ${{ secrets.acr_restapi01_password }}
        secret-name: triforktestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: trifork-testbd001
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          restapi01.azurecr.io/triforktest:${{ github.sha }}
        imagepullsecrets: |
          triforktestdockerauth
